name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6 # Ou a versão que preferir

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar código Terraform
        run: terraform validate

      - name: Executar Terraform Plan
        run: terraform plan -input=false

